{
  ...
}:
{
  imports = [
    ./hardware-configuration.nix
    ../../modules/kernel/cachyos.nix
    ../../modules/base.nix
    ../../modules/sway.nix
    ../../modules/audio.nix
    ../../modules/terminal.nix
    ../../modules/bluetooth.nix
    ../../modules/networking.nix
    ../../modules/user.nix
    ../../modules/gaming.nix
    ../../modules/nix-ld.nix
    ../../modules/virtualisation.nix
    ../../modules/power.nix
    ../../modules/mediaserver.nix
  ];
}
