{
  config,
  pkgs,
  lib,
  inputs,
  system,
  ...
}:

let
  cfg = config.custom.claude.notifications;

  hookEntry = {
    type = "command";
    command = "~/.claude/hooks/notify.sh";
  };

  # A hook is needed when notifications are enabled and at least one channel is on
  anyChannelEnabled = cfg.channels.desktop || cfg.channels.push || cfg.channels.popup;
  hooksNeeded = cfg.enable && anyChannelEnabled;

  hooks =
    lib.optionalAttrs (hooksNeeded && cfg.events.Stop) {
      Stop = [
        {
          hooks = [ hookEntry ];
        }
      ];
    }
    // lib.optionalAttrs (hooksNeeded && cfg.events.Notification) {
      Notification = [
        {
          matcher = "";
          hooks = [ hookEntry ];
        }
      ];
    };

  notifyConf = pkgs.writeText "notify.conf" ''
    # Generated by NixOS — do not edit
    NOTIFY_DESKTOP=${if cfg.channels.desktop then "1" else "0"}
    NOTIFY_PUSH=${if cfg.channels.push then "1" else "0"}
    NOTIFY_POPUP=${if cfg.channels.popup then "1" else "0"}
    NOTIFY_EVENT_STOP=${if cfg.events.Stop then "1" else "0"}
    NOTIFY_EVENT_NOTIFICATION=${if cfg.events.Notification then "1" else "0"}
  '';

  claudeSettings = {
    model = "opus";
    hooks = hooks;
    enabledPlugins = {
      "rust-analyzer-lsp@claude-plugins-official" = true;
      "skill-creator@claude-plugins-official" = true;
      "pyright-lsp@claude-plugins-official" = true;
      "gopls-lsp@claude-plugins-official" = true;
      "frontend-design@claude-plugins-official" = true;
      "semgrep@claude-plugins-official" = true;
      "superpowers@claude-plugins-official" = true;
      "feature-dev@claude-plugins-official" = true;
      "sonatype-guide@claude-plugins-official" = true;
      "code-simplifier@claude-plugins-official" = true;
      "commit-commands@claude-plugins-official" = true;
      "claude-md-management@claude-plugins-official" = true;
      "pr-review-toolkit@claude-plugins-official" = true;
      "claude-code-setup@claude-plugins-official" = true;
      "example-skills@anthropic-agent-skills" = true;
    };
    sandbox = {
      autoAllowBashIfSandboxed = true;
      network = {
        allowedDomains = [
          "github.com"
          "api.github.com"
          "npmjs.org"
          "registry.npmjs.org"
          "pypi.org"
          "crates.io"
        ];
      };
      filesystem = {
        denyRead = [
          "~/.ssh"
          "~/.gnupg"
          "~/.config/sops"
        ];
      };
    };
    effortLevel = "high";
    statusLine = {
      type = "command";
      command = "~/.claude/statusline.sh";
      padding = 1;
    };
  };

  claude-squad = pkgs.symlinkJoin {
    name = "claude-squad-wrapped";
    paths = [ inputs.claude-squad.packages.${system}.default ];
    buildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
      wrapProgram $out/bin/claude-squad --prefix PATH : ${
        lib.makeBinPath [
          pkgs.tmux
          pkgs.gh
          pkgs.git
        ]
      }
    '';
  };

  cs-wrapper = pkgs.writeShellScriptBin "cs" ''
    GIT_ROOT=$(${pkgs.git}/bin/git rev-parse --show-toplevel 2>/dev/null)

    if [ -n "$GIT_ROOT" ]; then
      export CLAUDE_SQUAD_HOME="$GIT_ROOT/.claude-squad"
      mkdir -p "$CLAUDE_SQUAD_HOME"
      if ! grep -q "^.claude-squad" "$GIT_ROOT/.gitignore" 2>/dev/null; then
        echo ".claude-squad/" >> "$GIT_ROOT/.gitignore"
      fi
    fi

    exec ${claude-squad}/bin/claude-squad "$@"
  '';

  tail-claude = pkgs.buildGoModule rec {
    pname = "tail-claude";
    version = "0.3.5";
    src = pkgs.fetchFromGitHub {
      owner = "kylesnowschwartz";
      repo = "tail-claude";
      rev = "v${version}";
      hash = "sha256-bKmcdjO1vWumgW5zqJf3wUPI3XPgqSof3PtI98NY/Oc=";
    };
    vendorHash = "sha256-BE+tZvkjR36cN0SGjUZNylU2J58FVUZfpFw3+2ObfNc=";
    env.CGO_ENABLED = 0;
  };
in
{
  options.custom.claude.notifications = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Master toggle for Claude Code notification hooks.";
    };
    channels = {
      desktop = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable desktop notifications via notify-send/swaync.";
      };
      push = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable push notifications via ntfy.sh.";
      };
      popup = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable claude-popup scratchpad notifications.";
      };
    };
    events = {
      Stop = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Fire notifications on Stop events.";
      };
      Notification = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Fire notifications on Notification events.";
      };
    };
  };

  config = {
    home.packages = [
      inputs.claude-code-nix.packages.${system}.default
      pkgs.jq
      pkgs.bun
      cs-wrapper
      tail-claude
      (pkgs.mcp-nixos.overridePythonAttrs { doCheck = false; })
    ];

    home.sessionVariables = {
      CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "true";
      CLAUDE_CODE_EFFORT_LEVEL = "max";
    };

    home.sessionPath = [
      "$HOME/.bun/bin"
    ];

    home.file.".claude/settings.json".text = builtins.toJSON claudeSettings;

    home.file.".claude/hooks/notify.sh" = lib.mkIf hooksNeeded {
      source = ../../config/claude/hooks/notify.sh;
      executable = true;
    };

    home.file.".claude/hooks/notify.conf" = lib.mkIf hooksNeeded {
      source = notifyConf;
    };

    home.file.".claude/statusline.sh" = {
      source = ../../config/claude/statusline.sh;
      executable = true;
    };

    sops.secrets.claude_code_oauth_token = { };
    programs.zsh.envExtra = ''
      export CLAUDE_CODE_OAUTH_TOKEN="$(cat ${config.sops.secrets.claude_code_oauth_token.path})"
    '';
  };
}
