eval $(ssh-agent) > /dev/null 2> /dev/null
ssh-add ~/.ssh/$HOST > /dev/null 2> /dev/null
export PATH="/home/aidanb/.emacs.d/bin:$PATH"
alias updaten="sudo nixos-rebuild switch --flake ~/System#$HOST"
alias hibernate="sudo systemctl hibernate"
eval "$(direnv hook zsh)"
